; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:WS-ESP32-S3-LCD-1-91]
platform        = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board           = WS-ESP32-S3-LCD-1-91   
framework       = arduino


board_upload.flash_size    = 16MB
board_upload.maximum_size  = 16777216
board_build.partitions     = partitions.csv ; default_16MB.csv 


build_flags =
    -DBOARD_HAS_PSRAM                        
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -Ilib
    -DLV_CONF_INCLUDE_SIMPLE

board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

monitor_speed = 115200
upload_speed = 921600


lib_deps =
        git+https://github.com/schreibfaul1/ESP32-audioI2S.git#e0668924480d81f370768e4dcb78f306748ff2de
        lvgl/lvgl@^9.5.0
