 #include <Arduino.h>
 #include "esp_log.h"
 #include "display_manager.h"
 #include "ui.h" // UI header generated by SquareLine Studio

// https://www.youtube.com/nishad2m8
// https://buymeacoffee.com/nishad2m8
 
 static const char *TAG = "main";
 
 void setup() {
   Serial.begin(115200);
   ESP_LOGI(TAG, "Application starting...");
   
   // Initialize display and LVGL
   esp_err_t ret = display_init();
   if (ret != ESP_OK) {
     ESP_LOGE(TAG, "Display initialization failed with error: %d", ret);
     return;
   }
   
   // Initialize UI
   if (display_lvgl_lock(-1)) {
     ESP_LOGI(TAG, "Initializing UI");

     ui_init(); // Initialize UI components

     display_lvgl_unlock();
     ESP_LOGI(TAG, "UI initialization complete");
   } else {
     ESP_LOGE(TAG, "Failed to acquire LVGL mutex for UI initialization");
   }
   
   ESP_LOGI(TAG, "Setup complete");
 }
 
 void loop() {
   // Main loop is empty as LVGL task handles UI updates
   vTaskDelay(pdMS_TO_TICKS(1000));
 }