#include <Arduino.h>
#include "WiFi.h"
#include "Audio.h"
#include "esp_log.h"
#include "display_manager.h"
#include "ui.h" // UI header generated by SquareLine Studio

// https://www.youtube.com/nishad2m8
// https://buymeacoffee.com/nishad2m8

static const char *TAG = "main";

// I2S pin definitions
#define I2S_BCLK 4
#define I2S_LRC 10
#define I2S_DOUT 11

// WiFi credentials
const char *ssid = "Galaxy S10e Poy";
const char *password = "17042022";

Audio audio;

void setup()
{
  Serial.begin(115200);
  ESP_LOGI(TAG, "Application starting...");

  // Initialize display and LVGL
  esp_err_t ret = display_init();
  if (ret != ESP_OK)
  {
    ESP_LOGE(TAG, "Display initialization failed with error: %d", ret);
    return;
  }

  // Initialize UI
  if (display_lvgl_lock(-1))
  {
    ESP_LOGI(TAG, "Initializing UI");

    ui_init(); // Initialize UI components

    display_lvgl_unlock();
    ESP_LOGI(TAG, "UI initialization complete");
  }
  else
  {
    ESP_LOGE(TAG, "Failed to acquire LVGL mutex for UI initialization");
  }

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(500);
    Serial.print(".");
  }
  Serial.println("nConnected to WiFi");

  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
  audio.setVolume(8); // 0..21

  // Replace with any Icecast/Shoutcast stream URL
  audio.connecttohost("http://icecast.radiofrance.fr/fip-midfi.mp3");

  ESP_LOGI(TAG, "Setup complete");
}

void loop()
{
  // Main loop is empty as LVGL task handles UI updates
  vTaskDelay(pdMS_TO_TICKS(1));
  audio.loop();
}