#include <Arduino.h>
#include <SD_MMC.h>
#include "Audio.h"
#include "esp_log.h"
#include "display_manager.h"
#include "ui.h" // UI header generated by SquareLine Studio
#include "config.h"


static const char *TAG = "main";

Audio audio;

void audio_info(const char *info)
{
  Serial.printf("[AUDIO] %s\n", info);
}


void audio_showstreamtitle(const char *info)
{
  Serial.printf("[TITLE] %s\n", info);
}

void audio_eof_mp3(const char *info)
{
  Serial.printf("[EOF] %s\n", info);
}

void setup()
{
    Serial.begin(115200);
    delay(1000);

    ESP_LOGI(TAG, "Application starting...");

    // --------------------------------------------------
    // DISPLAY
    // --------------------------------------------------
    esp_err_t ret = display_init();

    if (ret != ESP_OK)
    {
        ESP_LOGE(TAG, "Display initialization failed: %d", ret);
        return;
    }

    if (display_lvgl_lock(-1))
    {
        ESP_LOGI(TAG, "Initializing UI");
        ui_init();
        display_lvgl_unlock();
        ESP_LOGI(TAG, "UI initialization complete");
    }
    else
    {
        ESP_LOGE(TAG, "Failed to acquire LVGL mutex");
    }

    // --------------------------------------------------
    // SD CARD
    // --------------------------------------------------
    ESP_LOGI(TAG, "Initializing SD_MMC...");

    SD_MMC.setPins(
        SD_MMC_CLK,
        SD_MMC_CMD,
        SD_MMC_D0
    );

    if (!SD_MMC.begin("/sdcard", true))
    {
        ESP_LOGE(TAG, "SD_MMC initialization FAILED");
        return;
    }

    ESP_LOGI(TAG, "SD_MMC initialized");

    uint8_t cardType = SD_MMC.cardType();

    if (cardType == CARD_NONE)
    {
        ESP_LOGE(TAG, "No SD card detected");
        return;
    }

    uint64_t cardSize = SD_MMC.cardSize() / (1024 * 1024);

    ESP_LOGI(TAG, "SD card size: %llu MB", cardSize);

    // --------------------------------------------------
    // CHECK MP3 FILE
    // --------------------------------------------------
    if (!SD_MMC.exists("/test.mp3"))
    {
        ESP_LOGE(TAG, "/test.mp3 NOT FOUND");

        File root = SD_MMC.open("/");
        File file = root.openNextFile();

        while (file)
        {
            ESP_LOGI(TAG, "FILE: %s (%u bytes)",
                     file.name(),
                     (unsigned int)file.size());

            file = root.openNextFile();
        }

        return;
    }

    File mp3 = SD_MMC.open("/test.mp3");

    if (!mp3)
    {
        ESP_LOGE(TAG, "Cannot open /test.mp3");
        return;
    }

    ESP_LOGI(TAG, "MP3 found: %u bytes",
             (unsigned int)mp3.size());

    mp3.close();

    // --------------------------------------------------
    // AUDIO I2S
    // --------------------------------------------------
    ESP_LOGI(TAG, "Initializing I2S...");

    audio.setPinout(
        I2S_BCLK,
        I2S_LRC,
        I2S_DOUT
    );

    audio.setVolume(8);

    ESP_LOGI(TAG, "Starting MP3 playback...");

    audio.connecttoFS(SD_MMC, "/test.mp3");

    ESP_LOGI(TAG, "Setup complete");
}

void loop()
{
  // Main loop is empty as LVGL task handles UI updates
  vTaskDelay(pdMS_TO_TICKS(1));
  audio.loop();
}